---
title: Droplet processing QC report
date: "`r format(Sys.time(), '%Y-%m-%d')`"
output:
  html_document:
    theme: cosmo
    toc: true
    toc_depth: 2
    toc_float: true
    df_print: paged
    self_contained: true
params:
  rmd: droplet_qc.Rmd
  sample_id: null
  metadata: null
  outdir: null
  features_matrix: null
  hto_matrix: null
  hto_prefix: HTO_
  pre_filtered: false
  cell_calling_algorithm: emptydrops
  emptydrops_umi_min: 500
  emptydrops_umi_min_frac_median: 0.01
  emptydrops_cand_max_n: 20000
  emptydrops_ind_min: 45000
  emptydrops_ind_max: 90000
  emptydrops_niters: 10000
  multimodal_modalities:
    - gex
    - atac
    - adt
  multimodal_ordmag_quantile: 0.99
  multimodal_ordmag_ratio: 10
  demuxmix_model: auto
  demuxmix_pAcpt: 0.9
  multiplet_calling: true
  scdblfinder_clusters: true
  scdblfinder_dbr_sd: 1
  multiplet_projection: TSNE
---

```{r setup, include=FALSE}
# Set chunk options
knitr::opts_chunk$set(
  echo = FALSE,
  error = TRUE,
  message = FALSE,
  warning = FALSE,
  comment = "",
  results = "asis"
)

# Load packages
library(dplyr)
library(ggplot2)
library(plotly)
library(Matrix)
library(DropletUtils)
library(demuxmix)
library(scuttle)
library(scater)
library(scran)
library(scDblFinder)

# Check if running within Snakemake pipeline
if (exists("snakemake")) {
  # if running within Snakemake pipeline
  log <- file(snakemake@log[[1]], open = "w")
  sink(log, type = "message") # write stderr to Snakemake log file

  snakemake@source("utils.R")

  unlockBinding("params", .GlobalEnv)
  params$sample_id <- snakemake@wildcards$sample
  params <- update.params(snakemake@params)
  lockBinding("params", .GlobalEnv)

  if (!dir.exists(dirname(snakemake@output[[1]]))) dir.create(dirname(snakemake@output[[1]]), recursive = TRUE)
} else {
  # if running in isolation
  source("utils.R")
}

# Replace path placeholders and validate params
unlockBinding("params", .GlobalEnv)
for (x in c("outdir", "features_matrix", "hto_matrix")) {
  params[[x]] <- glue::glue(params[[x]], sample = params$sample_id)
  if (length(params[[x]]) == 0) params[[x]] <- NULL # override default value of glue::glue() for null input (character(0)) and return null output
}
params$cell_calling_algorithm <- match.arg(tolower(params$cell_calling_algorithm), choices = c("emptydrops", "multimodal", "combined"))
params$multimodal_modalities <- match.arg(tolower(params$multimodal_modalities), choices = c("gex", "atac", "adt"), several.ok = TRUE)
params$demuxmix_model <- match.arg(tolower(params$demuxmix_model), choices = c("auto", "naive"))
params$multiplet_projection <- match.arg(toupper(params$multiplet_projection), choices = c("TSNE", "UMAP"))
lockBinding("params", .GlobalEnv)

# Check for missing required params
required <- c(
  "sample_id",
  "metadata",
  "outdir",
  "features_matrix"
)
is.missing <- sapply(params[required], is.null)
if (any(is.missing)) {
  names <- paste(names(params[required])[is.missing], collapse = ", ")
  stop(sprintf("The following required parameters are missing: %s", names))
}

# Initialise barcodes list
bc <- list()

# Initialise list index
list.index <- 1
```

### Sample: `r params$sample_id`

# Overview

```{r overview}
cat(prepend.index("Load count matrices"), "\n")
if (!params$pre_filtered) {
  cat(prepend.index("Run cell calling algorithm to filter empty droplet barcodes"), "\n")
}
if (!is.null(params$hto_matrix)) {
  cat(prepend.index("Run HTO demultiplexing algorithm to classify barcodes as 'singlet' (with assigned HTO), 'multiplet', 'negative' or 'uncertain'"), "\n")
}
if (params$multiplet_calling) {
  if (is.null(params$hto_matrix)) {
    cat(prepend.index("Predict multiplets based on simulated doublets"), "\n")
  } else {
    cat(prepend.index("Predict intra-sample multiplets based on known inter-sample multiplets"), "\n")
  }
}
cat(prepend.index("Output TSV file containing barcode metadata"), "\n")
if (!params$pre_filtered) {
  cat(prepend.index("Output text file containing list of empty droplet barcodes"), "\n")
}
```

# Data loading

```{r load-metadata}
cat("* **Metadata:**", params$metadata, "\n")
md <- vroom::vroom(
  params$metadata,
  delim = ",",
  col_names = TRUE,
  show_col_types = FALSE
) %>%
  filter(sample_id == params$sample_id) %>%
  as.data.frame()
wl <- md$hto
```

```{r load-features-matrix}
cat("* **Features matrix:**", params$features_matrix, "\n")
features.mat <- get.10x.h5(params$features_matrix)
bc$features <- colnames(features.mat[[1]])
```

```{r load-hto-matrix, eval=!is.null(params$hto_matrix)}
cat("* **HTO matrix:**", params$hto_matrix, "\n")
if (grepl(pattern = ".mtx.gz$", x = params$hto_matrix)) {
  hto.mat <- get.10x.matrix(params$hto_matrix, type = c("Antibody Capture", "Multiplexing Capture"))
} else {
  hto.mat <- get.barcounter.matrix(params$hto_matrix, features.pattern = paste0("^", params$hto_prefix))
}
hto.mat <- hto.mat[match(wl, rownames(hto.mat)), ]
hto.mat <- hto.mat[, colSums(hto.mat) > 0] # remove cell barcodes with zero counts
bc$hto <- colnames(hto.mat)
```

# Data processing

```{r no-cell-calling, eval=params$pre_filtered}
cells.loaded <- md$cells_loaded %>% 
  sum() %>%
  ifelse(. > 0, ., NA)
bc.cells <- Reduce(intersect, bc)
cc.stats <- list("loaded" = cells.loaded, "cells" = length(bc.cells), "empty" = NA, "limited" = NA)
features.mat[["Gene Expression"]] <- features.mat[["Gene Expression"]][, bc.cells]
```

```{r cell-calling, eval=!params$pre_filtered}
cat("## Cell calling {.tabset}", "\n\n")
modalities <- names(features.mat) %>%
  case_match(
    "Gene Expression" ~ "gex",
    "Peaks" ~ "atac",
    "Antibody Capture" ~ "adt"
  )
total.counts <- mapply(
  function(mat, type) {
    data.frame(colSums(mat)) %>%
      setNames(type) %>%
      tibble::rownames_to_column("barcode")
  },
  mat = features.mat,
  type = modalities,
  SIMPLIFY = FALSE
) %>%
  Reduce(
    x = .,
    f = function(x, y) full_join(x, y, by = "barcode")
  ) %>%
  filter(if_all(everything(), function(x) !is.na(x)))

cells <- list()
empty <- list()
cc.stats <- list("loaded" = NA, "cells" = 0, "empty" = 0, "limited" = NA)

cells.loaded <- md$cells_loaded %>%
  sum() %>%
  ifelse(. > 0, ., NA)
cc.stats$loaded <- cells.loaded
if (!is.na(cells.loaded)) {
  expected.cells <- cells.loaded * 0.625 # ~62.5% capture rate of cells loaded as per 10x documentation
} else {
  expected.cells <- estimate.expected.cells(colSums(features.mat[["Gene Expression"]])) # if cells loaded not available, emprically estimate expected cells using GEX UMI counts
}

if (params$cell_calling_algorithm %in% c("multimodal", "combined")) {
  cc.res <- multimodal.cell.caller(
    matrix.list = features.mat,
    n.expected.cells = expected.cells,
    ordmag.quantile = params$multimodal_ordmag_quantile,
    ordmag.ratio = params$multimodal_ordmag_ratio
  )
  cells$multi <- bc$features[bc$features %in% cc.res]
  empty$multi <- bc$features[!(bc$features %in% cc.res)]
}
if (params$cell_calling_algorithm %in% c("emptydrops", "combined")) {
  set.seed(100)
  cc.res <- emptyDropsCellRanger(
    features.mat[["Gene Expression"]],
    n.expected.cells = expected.cells,
    umi.min = params$emptydrops_umi_min,
    umi.min.frac.median = params$emptydrops_umi_min_frac_median,
    cand.max.n = params$emptydrops_cand_max_n,
    ind.min = params$emptydrops_ind_min,
    ind.max = params$emptydrops_ind_max,
    niters = params$emptydrops_niters
  )
  cells$ed <- bc$features[which(cc.res$FDR < 0.001)]
  empty$ed <- bc$features[which(cc.res$FDR >= 0.001 | is.na(cc.res$FDR))]
  cc.stats$limited <- any(cc.res$Limited[which(cc.res$FDR >= 0.001)])
}
if (params$cell_calling_algorithm == "combined") {
  bc$features <- intersect(cells$multi, cells$ed)
  bc.empty <- intersect(empty$multi, empty$ed)
} else {
  bc$features <- cells[[1]]
  bc.empty <- empty[[1]]
}
bc.cells <- Reduce(intersect, bc)
cc.stats$cells <- length(bc.cells)
cc.stats$empty <- length(bc.empty)

bcrank.res <- barcodeRanks(features.mat[["Gene Expression"]])
features.mat[["Gene Expression"]] <- features.mat[["Gene Expression"]][, bc.cells]
```

```{r cell-calling-classification, eval=!params$pre_filtered}
cat("### Classification", "\n\n")
cat("* **Cell-containing droplets:**", cc.stats$cells %>% format(big.mark = ","), "\n")
cat("* **Empty droplets:**", cc.stats$empty %>% format(big.mark = ","), "\n")
cat("\n\n")
ggplotly(
  bcrank.plot(
    bcrank.res,
    cells = bc.cells,
    title = "Barcode rank plot",
    x.lab = "Rank",
    y.lab = "GEX UMI count",
    colour.lab = "Fraction cells",
    log = TRUE
  ) +
    scale_colour_gradient2(low = "#d82526", mid = "#ffc156", high = "#69b764", midpoint = 0.5)
)
```

```{r cell-calling-cross-sensitivities, eval=all(!params$pre_filtered, length(features.mat) > 1)}
cat("### Cross-sensitivities", "\n\n")
for (comb in combn(modalities, 2, FUN = c, simplify = FALSE)) {
  plot <- scatter.plot(
    data = total.counts %>%
      mutate(type = if_else(barcode %in% bc.cells, "Cell", "Empty")) %>%
      arrange(desc(type)) %>%
      select(all_of(comb), type) %>%
      distinct(),
    x = !!sym(comb[1]),
    y = !!sym(comb[2]),
    colour = type,
    size = 0.1,
    title = paste(toupper(comb[1]), "vs", toupper(comb[2]), sep = " "),
    x.lab = paste(toupper(comb[1]), if_else(comb[1] == "atac", "peak read", "UMI"), "count", sep = " "),
    y.lab = paste(toupper(comb[2]), if_else(comb[2] == "atac", "peak read", "UMI"), "count", sep = " "),
    log = TRUE
  ) +
    scale_colour_manual(values = list(Cell = "#69b764", Empty = "lightgrey"))
  print(plot)
}
```

```{r cell-calling-diagnostics, eval=!params$pre_filtered}
cat("### Diagnostics", "\n\n")
cat("* **Algorithm:**", params$cell_calling_algorithm, "\n")
if (params$cell_calling_algorithm %in% c("multimodal", "combined")) {
  cat("* **Modalities:**", toupper(modalities) %>% paste(collapse = ", "), "\n")
  cat("* **OrdMag quantile:**", params$multimodal_ordmag_quantile %>% format(big.mark = ","), "\n")
  cat("* **OrdMag ratio:**", params$multimodal_ordmag_ratio %>% format(big.mark = ","), "\n")
}
if (params$cell_calling_algorithm %in% c("emptydrops", "combined")) {
  cat("* **Minimum UMI count (absolute):**", params$emptydrops_umi_min %>% format(big.mark = ","), "\n")
  cat("* **Minimum UMI count (fraction of median):**", params$emptydrops_umi_min_frac_median %>% format(big.mark = ","), "\n")
  cat("* **Maximum number of candidate cells:**", params$emptydrops_cand_max_n %>% format(big.mark = ","), "\n")
  cat("* **Ambient estimation range:**", params$emptydrops_ind_min %>% format(big.mark = ","), "-", params$emptydrops_ind_max %>% format(big.mark = ","), "\n")
  cat("* **Monte Carlo simulation iterations:**", params$emptydrops_niters %>% format(big.mark = ","), "\n")
  cat("* **Limited:**", ifelse(cc.stats$limited, "Yes", "No"), "\n")
}
```

```{r hto-demultiplexing, eval=!is.null(params$hto_matrix)}
cat("## HTO demultiplexing {.tabset}", "\n\n")
set.seed(100)
hto.mat <- hto.mat[, bc.cells]
dmm <- demuxmix(
  hto = as.matrix(hto.mat),
  rna = colSums(features.mat[["Gene Expression"]]),
  model = params$demuxmix_model,
  pAcpt = params$demuxmix_pAcpt^length(wl)
)
models <- lapply(dmm@models, function(x) class(x))
demux.res <- dmm %>%
  dmmClassify() %>%
  mutate(HTO = if_else(grepl(",", HTO), "multiplet", HTO))
demux.stats <- demux.res %>%
  as.data.frame() %>%
  group_by(HTO) %>%
  summarise(count = n())
demux.stats <- demux.stats$count %>%
  as.list() %>%
  setNames(demux.stats$HTO)
demux.stats$singlet <- sum(demux.res$Type == "singlet")
bc.cells <- demux.res %>%
  filter(Type %in% c("singlet", "multiplet")) %>%
  rownames()
features.mat[["Gene Expression"]] <- features.mat[["Gene Expression"]][, bc.cells]
```

```{r hto-demultiplexing-classification, eval=!is.null(params$hto_matrix)}
cat("### Classification", "\n\n")
cat(sprintf("* **%s:** %s", names(demux.stats)[names(demux.stats) != "singlet"], format(as.integer(demux.stats[names(demux.stats) != "singlet"]), big.mark = ",")) %>% paste(collapse = "\n"), "\n")
cat("\n\n")
ggplotly(
  bar.plot(
    data = demux.res %>% mutate(Type = factor(Type, levels = c("singlet", "multiplet", "negative", "uncertain"))),
    pos = Type,
    fill = HTO,
    position = position_stack(reverse = TRUE),
    title = "HTO assignment",
    pos.lab = "Type",
    fill.lab = "HTO"
  ),
  tooltip = c("fill", "x")
)
```

```{r hto-demultiplexing-raw-counts, eval=!is.null(params$hto_matrix), fig.width=7, fig.height=length(wl)}
cat("### Raw HTO counts", "\n\n")
logcounts.plot(
  hto.mat,
  scale = 0.95,
  colour = NA,
  fill = "#595959",
  title = "Raw HTO counts"
)
```

```{r hto-demultiplexing-demux-counts, eval=!is.null(params$hto_matrix), fig.width=7, fig.height=3*ceiling(length(wl)/2)}
cat("### Demultiplexed HTO counts", "\n\n")
logcounts.plot(
  hto.mat,
  samples = demux.res$HTO,
  scale = 0.95,
  colour = NA,
  show.legend = FALSE,
  title = "Demultiplexed HTO counts"
)
```

```{r hto-demultiplexing-mixture-components, eval=!is.null(params$hto_matrix), fig.width=7, fig.height=2.5}
cat("### Mixture components", "\n\n")
for (x in wl) {
  plot <- plotDmmHistogram(dmm, hto = x) +
    labs(title = x, x = "UMI count") +
    theme_minimal()
  print(plot)
}
```

```{r hto-demultiplexing-diagnostics, eval=!is.null(params$hto_matrix)}
cat("### Diagnostics", "\n\n")
cat("* **Mode:**", params$demuxmix_model, "\n")
cat("* **Chosen model:**", "\n")
cat(sprintf("  + **%s:** %s", wl, models[wl]) %>% paste(collapse = "\n"), "\n")
cat("* **Acceptance probability:**", params$demuxmix_pAcpt^length(wl) %>% round(2), paste0("(", params$demuxmix_pAcpt %>% round(2), " per HTO)"), "\n")
cat("* **Fraction overlap between mixture components:**", "\n")
cat(sprintf("  + **%s:** %s", wl, round(dmmOverlap(dmm)[wl], 3)) %>% paste(collapse = "\n"), "\n")
```

```{r multiplet-calling, eval=params$multiplet_calling}
cat("## Multiplet calling {.tabset}", "\n\n")
set.seed(100)
known <- if (exists("demux.res")) demux.res[colnames(features.mat[["Gene Expression"]]), "Type"] == "multiplet" else rep(FALSE, times = ncol(features.mat[["Gene Expression"]]))
sce <- SingleCellExperiment(assays = list(counts = features.mat[["Gene Expression"]])) %>% logNormCounts()
dec <- modelGeneVar(sce)
hvg <- getTopHVGs(dec, n = 1000)
sce <- sce %>% runPCA(subset_row = hvg, ncomponents = 20)
if (any(known)) {
  # If known inter-sample multiplets available, use nearest neighbours-based intra-sample multiplet prediction
  multiplet.res <- recoverDoublets(
    x = sce,
    use.dimred = "PCA",
    doublets = known,
    samples = table(demux.res$HTO[demux.res$Type %in% c("singlet", "multiplet")]) %>% head(-1)
  ) %>%
    as.data.frame() %>%
    select(known, predicted)
  rownames(multiplet.res) <- colnames(sce)
} else {
  # Otherwise, use simulation-based multiplet prediction
  multiplet.res <- scDblFinder(
    sce = sce,
    nfeatures = hvg,
    clusters = params$scdblfinder_clusters,
    dbr.sd = params$scdblfinder_dbr_sd,
    returnType = "table"
  ) %>%
    as.data.frame() %>%
    filter(type == "real")
  multiplet.res <- multiplet.res[colnames(sce), ]
  multiplet.res <- transmute(
    multiplet.res,
    known = known,
    predicted = if_else(class == "doublet", TRUE, FALSE)
  )
}
multiplet.stats <- list(
  known = sum(multiplet.res$known, na.rm = TRUE),
  predicted = sum(multiplet.res$predicted, na.rm = TRUE),
  singlet = sum(!multiplet.res$known & !multiplet.res$predicted, na.rm = TRUE)
)
multiplet.stats$multiplet <- sum(multiplet.stats$known, multiplet.stats$predicted, na.rm = TRUE)
bc.cells <- multiplet.res %>%
  filter(!known & !predicted) %>%
  rownames()
```

```{r multiplet-calling-classification, eval=params$multiplet_calling}
cat("### Classification", "\n\n")
cat("* **Singlets:**", multiplet.stats$singlet %>% format(big.mark = ","), "\n")
cat("* **Known (inter-sample) multiplets:**", multiplet.stats$known %>% format(big.mark = ","), "\n")
cat("* **Predicted (intra-sample) multiplets:**", multiplet.stats$predicted %>% format(big.mark = ","), "\n")
cat("\n\n")
ggplotly(
  multiplet.plot(
    sce,
    multiplet.res,
    size = 0.1,
    projection = params$multiplet_projection,
    use.dimred = "PCA",
    random.seed = 100
  ),
  tooltip = "colour"
)
```

# Summary

```{r output}
metadata <- data.frame(
  barcode = bc.cells,
  sample_id = params$sample_id
)
metadata$hash_id <- if (exists("demux.res")) sapply(demux.res[metadata$barcode, ]$HTO, function(x) md[md$hto == x, "hash_id", drop = TRUE]) else md[1, "hash_id", drop = TRUE]
metadata <- left_join(metadata, md %>% select(-c(hto, cells_loaded)) %>% distinct(), by = c("sample_id", "hash_id"))
if (length(unique(metadata$hash_id)) == 1) metadata$hash_id <- NULL # remove hash_id column if all values are the same (i.e. no cell hashing)
summary.stats <- cc.stats[c("loaded", "cells")] %>%
  as.data.frame() %>%
  dplyr::rename(
    cells_loaded = loaded,
    cells_recovered = cells
  )
if (exists("demux.stats")) {
  summary.stats <- summary.stats %>%
    cbind(demux.stats[c("singlet", "multiplet", "negative", "uncertain")]) %>%
    mutate(
      undetermined = negative + uncertain
    )
}
if (exists("multiplet.stats")) {
  summary.stats$singlet <- multiplet.stats$singlet
  summary.stats$multiplet <- multiplet.stats$multiplet
}
summary.stats <- summary.stats[, match(c("cells_loaded", "cells_recovered", "singlet", "multiplet", "undetermined"), colnames(summary.stats), nomatch = 0), drop = FALSE] %>%
  mutate(
    across(
      .cols = !starts_with("cells_"),
      .fns = function(x) x / cells_recovered,
      .names = "fraction_{.col}"
    )
  )

if (!dir.exists(params$outdir)) dir.create(params$outdir, recursive = TRUE)
vroom::vroom_write(
  metadata,
  file = file.path(params$outdir, "metadata.tsv"),
  delim = "\t"
)
vroom::vroom_write(
  summary.stats,
  file = file.path(params$outdir, "barcode_stats.tsv"),
  delim = "\t"
)
if (exists("dmm")) {
  vroom::vroom_write(
    dmmOverlap(dmm)[wl] %>%
      as.matrix() %>%
      t() %>%
      as.data.frame(),
    file = file.path(params$outdir, "hto_signal.tsv"),
    delim = "\t"
  )
}
if (exists("bc.empty")) {
  vroom::vroom_write_lines(
    bc.empty,
    file = file.path(params$outdir, "empty_droplet_barcodes.txt")
  )
}

cc.excluded <- if (exists("cc.stats")) cc.stats$empty else NA
demux.excluded <- if (exists("demux.stats")) sum(demux.stats$negative, demux.stats$uncertain, na.rm = TRUE) else NA
multiplet.excluded <- if (exists("multiplet.stats")) sum(multiplet.stats$known, multiplet.stats$predicted, na.rm = TRUE) else NA
cat("* **Total barcodes passed:**", length(bc.cells) %>% format(big.mark = ","), "\n")
cat("* **Total barcodes excluded:**", sum(cc.excluded, demux.excluded, multiplet.excluded, na.rm = TRUE) %>% format(big.mark = ","), "\n")
if (!is.na(cc.excluded)) cat("  + **Empty droplets:**", cc.excluded %>% format(big.mark = ","), "\n")
if (!is.na(demux.excluded)) cat("  + **Negative/uncertain HTO:**", demux.excluded %>% format(big.mark = ","), "\n")
if (!is.na(multiplet.excluded)) cat("  + **Multiplets:**", multiplet.excluded %>% format(big.mark = ","), "\n")
```

# Session Info

```{r session-info, results="markup"}
sessionInfo()
```

# Source
This report was automatically generated from an R Markdown script (<a download="droplet_qc.Rmd" href="`r base64enc::dataURI(file = params$rmd, mime = 'text/rmd', encoding = 'base64')`">download source</a>).
