##########################################################################################
# Configuration file for Snakemake pipeline
# Author: Redwan Farooq
# Complete ALL entries in sections marked 'REQUIRED'
# Comment ('#') any unused entries in sections marked 'OPTIONAL'
##########################################################################################


# --------------------------------------------------
# Module
# --------------------------------------------------
# REQUIRED
# Pipeline module for experimental design
# Options:
#   qc
#     Additional required configuration:
#       - 'gex_matrix' (input/output)
#       - 'hto_matrix' (input/output)
module: qc


# --------------------------------------------------
# Input/output
# --------------------------------------------------
# REQUIRED
# Output directories
output_dir:
  data: /project/fuggerlab/rfarooq/project/ocrelizumab_multiome/data/processed/qc
  reports: /project/fuggerlab/rfarooq/project/ocrelizumab_multiome/results/reports/qc

# OPTIONAL
# File paths for count matrices (use {sample} as placeholder for sample name)
gex_matrix: /project/fuggerlab/rfarooq/project/ocrelizumab_multiome/data/raw/tea_seq/test/cellranger_arc/{sample}/outs/raw_feature_bc_matrix/matrix.mtx.gz
hto_matrix: /project/fuggerlab/rfarooq/project/ocrelizumab_multiome/data/raw/tea_seq/test/barcounter/{sample}/{sample}_Tag_Counts.csv
atac_matrix: /project/fuggerlab/rfarooq/project/ocrelizumab_multiome/data/raw/tea_seq/test/cellranger_arc/{sample}/outs/raw_feature_bc_matrix/matrix.mtx.gz
adt_matrix: /project/fuggerlab/rfarooq/project/ocrelizumab_multiome/data/raw/tea_seq/test/barcounter/{sample}/{sample}_Tag_Counts.csv
# If 'scripts_dir' not specified, defaults to
# 'resources/scripts'
# scripts_dir:
# If 'rmd_dir' not specified, defaults to
# 'resources/rmarkdown'
# rmd_dir:
# If 'metadata_dir' not specified, defaults to
# 'metadata'
# metadata_dir:


# --------------------------------------------------
# Metadata files
# *** RELATIVE paths from 'metadata_dir' ***
# --------------------------------------------------
# REQUIRED
# Sample hashing summary table in CSV format
# Required fields:
#   donor: donor ID
#   hash: hash ID
#   sample: sample name
#   hto: hashtag antibody ID
#   cells_loaded: number of cells loaded
samples: samples.csv


# --------------------------------------------------
# Script parameters
# --------------------------------------------------
# OPTIONAL
# droplet_qc.Rmd
emptydrops_lower: 100 # default: 100
emptydrops_niters: 10000 # default: 10000
demuxmix_model: naive # default: auto; options: auto, naive (case-sensitive)
demuxmix_pAcpt: 0.8 # default: 0.9
multiplet_projection: TSNE # default: TSNE; options: TSNE, UMAP (case-sensitive)
# libraries_qc.Rmd
gex_filters:
  library_size: false # default: true
  library_complexity: false # default: true
  mitochondrial_fraction: true # default: true
atac_filters:
  peak_count: false # default: true
  peak_fraction: false # default: true
  blacklist_fraction: false # default: true
  nucleosome_signal: true # default: true
  tss_enrichment: true # default: true
adt_filters:
  isotype_control: ^ADT_Isotype_ # default: null; regex pattern for isotype control antibody IDs
