##########################################################################################
# Configuration file for Snakemake pipeline
# Author: Redwan Farooq
# Complete ALL entries in sections marked 'REQUIRED'
# Comment ('#') any unused entries in sections marked 'OPTIONAL'
##########################################################################################


# --------------------------------------------------
# Module
# --------------------------------------------------
# REQUIRED
# Pipeline module for experimental design
# Options:
#   qc
#     Additional required configuration:
#       - 'gex_matrix' (input/output)
module: qc


# --------------------------------------------------
# Input/output
# --------------------------------------------------
# REQUIRED
# Output directories
output_dir:
  data: /project/fuggerlab/rfarooq/project/jurkat_multiome/data/processed/gex_atac/qc
  reports: /project/fuggerlab/rfarooq/project/jurkat_multiome/results/reports/gex_atac/qc

# OPTIONAL
# File paths for count matrices (use {sample} as placeholder for sample name)
gex_matrix: /project/fuggerlab/rfarooq/project/jurkat_multiome/data/raw/gex_atac/starsolo/{sample}/Solo.out/GeneFull_Ex50pAS/raw/matrix.mtx.gz
# hto_matrix: /path/to/hto_dir/{sample}/file.ext
atac_matrix: /project/fuggerlab/rfarooq/project/jurkat_multiome/data/raw/gex_atac/chromap_macs2/{sample}/raw_feature_bc_matrix/matrix.mtx.gz
# adt_matrix: /path/to/adt_dir/{sample}/file.ext
# File path to TSV file containing total sequencing read counts per library type/sample
# MUST contain column 'sample' and 1 column per library type
read_counts: /project/fuggerlab/rfarooq/project/jurkat_multiome/data/raw/gex_atac/qc/count_reads/read_counts.tsv
# If 'scripts_dir' not specified, defaults to
# 'resources/scripts'
# scripts_dir:
# If 'metadata_dir' not specified, defaults to
# 'metadata'
# metadata_dir:


# --------------------------------------------------
# Metadata files
# *** RELATIVE paths from 'metadata_dir' ***
# --------------------------------------------------
# REQUIRED
# Sample hashing summary table in CSV format
# Required fields:
#   donor: donor ID
#   pool: pool ID
#   sample: sample name
#   hto: hashtag antibody ID (or 'None' if not used)
#   cells_loaded: number of cells loaded
samples: samples.csv


# --------------------------------------------------
# Script parameters
# --------------------------------------------------
# OPTIONAL
# droplet_qc.Rmd
pre_filtered: false # default: false
cell_calling_algorithm: combined # default: emptydrops; options: emptydrops, multimodal, combined
emptydrops_umi_min: 500 # default: 500
emptydrops_umi_min_frac_median: 0.01 # default: 0.01
emptydrops_cand_max_n: 20000 # default: 20000
emptydrops_ind_min: 45000 # default: 45000
emptydrops_ind_max: 90000 # default: 90000
emptydrops_niters: 10000 # default: 10000
multimodal_modalities: # default: gex, atac, adt; options: gex, atac, adt
  - gex
  - atac
  - adt
multimodal_ordmag_quantile: 0.99 # default: 0.99
multimodal_ordmag_ratio: 10 # default: 10
demuxmix_model: auto # default: auto; options: auto, naive
demuxmix_pAcpt: 0.9 # default: 0.9
multiplet_calling: false # default: true
scdblfinder_clusters: true # default: true
scdblfinder_dbr_sd: 1 # default: 1
multiplet_projection: TSNE # default: TSNE; options: TSNE, UMAP
# libraries_qc.Rmd
gex_filters:
  library_size: true # default: true
  library_complexity: true # default: true
  mitochondrial_fraction: true # default: true
atac_filters:
  peak_count: true # default: true
  peak_fraction: true # default: true
  blacklist_fraction: true # default: true
  nucleosome_signal: true # default: true
  tss_enrichment: true # default: true
adt_filters:
  isotype_control: null # default: null; regex pattern for isotype control antibody IDs
# ambient_removal.Rmd
control: null # default: null; control sample (i.e. cross-batch technical replicate)
gex_ambient_removal:
  skip: true # default: false
  integrate_samples: false # default: false
  cluster_ndims: 10 # default: 10
  cluster_k: 20 # default: 20
  cluster_res: 0.05 # default: 0.05
  cluster_markers: null # default: null; list of cluster marker gene symbols for diagnostic plots
adt_ambient_removal:
  skip: false # default: false
  integrate_samples: false # default: false
  cluster_ndims: 10 # default: 10
  cluster_k: 20 # default: 20
  cluster_res: 0.2 # default: 0.2
  cluster_markers: null # default: null; list of cluster marker ADT IDs (without 'ADT_' prefix) for diagnostic plots
# summary_report.qmd
target_depth:
  GEX: 20000 # default: 20000
  ATAC: 25000 # default: 25000
  ADT: 5000 # default: 5000
  HTO: 2000 # default: 2000
