##########################################################################################
# Configuration file for Snakemake pipeline
# Author: Redwan Farooq
# Complete ALL entries in sections marked 'REQUIRED'
# Comment ('#') any unused entries in sections marked 'OPTIONAL'
##########################################################################################


# --------------------------------------------------
# Module
# --------------------------------------------------
# REQUIRED
# Pipeline module for QC workflow
# Options:
#   default: Default pipeline (EmptyDrops/multimodal/combined cell calling, DecontX/DecontPro ambient removal)
#     Additional required configuration:
#       - 'gex_matrix' (input/output)
#   cellbender (CellBender cell calling/ambient removal)
#     Additional required configuration:
#       - 'gex_matrix' (input/output)
module: cellbender


# --------------------------------------------------
# Input/output
# --------------------------------------------------
# REQUIRED
# Output directories
output_dir:
  data: /project/fuggerlab/rfarooq/project/ocrelizumab_multiome/data/processed/cite_seq/cohort_01_cellbender/qc
  reports: /project/fuggerlab/rfarooq/project/ocrelizumab_multiome/results/reports/cite_seq/cohort_01_cellbender/qc

# OPTIONAL
# File paths for count matrices (use {sample} as placeholder for sample name)
gex_matrix: /project/fuggerlab/rfarooq/project/ocrelizumab_multiome/data/raw/cite_seq/cohort_01/starsolo/{sample}/Solo.out/GeneFull_Ex50pAS/raw/matrix.mtx.gz
hto_matrix: /project/fuggerlab/rfarooq/project/ocrelizumab_multiome/data/raw/cite_seq/cohort_01/barcounter/{sample}/{sample}_Tag_Counts.csv
# atac_matrix: /path/to/atac_dir/{sample}/file.ext
adt_matrix: /project/fuggerlab/rfarooq/project/ocrelizumab_multiome/data/raw/cite_seq/cohort_01/barcounter/{sample}/{sample}_Tag_Counts.csv
# File path to TSV file containing total sequencing read counts per library type/sample
# MUST contain column 'sample' and 1 column per library type
read_counts: /project/fuggerlab/rfarooq/project/ocrelizumab_multiome/data/raw/cite_seq/cohort_01/qc/count_reads/read_counts.tsv
# If 'scripts_dir' not specified, defaults to
# 'resources/scripts'
# scripts_dir:
# If 'metadata_dir' not specified, defaults to
# 'metadata'
# metadata_dir:


# --------------------------------------------------
# Metadata files
# *** RELATIVE paths from 'metadata_dir' ***
# --------------------------------------------------
# REQUIRED
# Sample hashing summary table in CSV format
# Required fields:
#   donor: donor ID
#   pool: pool ID
#   sample: sample name
#   hto: hashtag antibody ID (or 'None' if not used)
#   cells_loaded: number of cells loaded
samples: samples.csv


# --------------------------------------------------
# Script parameters
# --------------------------------------------------
# OPTIONAL
# Global parameters
adt_prefix: ADT_ # default: ADT_; prefix for ADT features
adt_isotype: Isotype # default: null; regex pattern for isotype control antibody IDs
hto_prefix: HTO_ # default: HTO_; prefix for HTO features (use 'CMO' if using 10x cell multiplexing kit with CellRanger built-in reference)
pre_filtered: false # default: false; set to true if input matrices are pre-filtered (i.e. only cell-containing barcodes) or if using CellBender for cell calling
# droplet_qc.Rmd
cell_calling_algorithm: multimodal # default: emptydrops; options: emptydrops, multimodal, combined; only 'multimodal' is supported if using CellBender
emptydrops_umi_min: 500 # default: 500
emptydrops_umi_min_frac_median: 0.01 # default: 0.01
emptydrops_cand_max_n: 20000 # default: 20000
emptydrops_ind_min: 45000 # default: 45000
emptydrops_ind_max: 90000 # default: 90000
emptydrops_niters: 10000 # default: 10000
multimodal_modalities: # default: gex, atac, adt; options: gex, atac, adt
  - gex
  - atac
  - adt
multimodal_ordmag_quantile: 0.99 # default: 0.99
multimodal_ordmag_ratio: 10 # default: 10
demuxmix_model: auto # default: auto; options: auto, naive
demuxmix_pAcpt: 0.9 # default: 0.9
multiplet_calling: true # default: true
scdblfinder_clusters: true # default: true
scdblfinder_dbr_sd: 1 # default: 1
multiplet_projection: TSNE # default: TSNE; options: TSNE, UMAP
# libraries_qc.Rmd
gex_filters:
  library_size: true # default: true
  library_complexity: true # default: true
  mitochondrial_fraction: true # default: true
atac_filters:
  peak_count: true # default: true
  peak_fraction: true # default: true
  blacklist_fraction: true # default: true
  nucleosome_signal: true # default: true
  tss_enrichment: true # default: true
adt_filters:
  zero_ambient: true # default: true; set to false if using CellBender
  high_ambient: true # default: true; set to false if using CellBender
  high_controls: true # default: true
# ambient_removal.Rmd
gex_ambient_removal:
  skip: false # default: false
  integrate_samples: true # default: false
  cluster_ndims: 10 # default: 10
  cluster_k: 20 # default: 20
  cluster_res: 0.05 # default: 0.05
  cluster_markers: # default: null; list of cluster marker gene symbols for diagnostic plots
    - CD3E
    - MS4A1
    - LYZ
    - FCGR3A
    - GNLY
    - PPBP
adt_ambient_removal:
  skip: true # default: false
  integrate_samples: false # default: false
  cluster_ndims: 10 # default: 10
  cluster_k: 20 # default: 20
  cluster_res: 0.2 # default: 0.2
  cluster_markers: # default: null; list of cluster marker ADT IDs (without 'ADT_' prefix) for diagnostic plots
    - CD3
    - CD4
    - CD8
    - CD19
    - CD14
    - CD16
# summary_report.qmd
target_depth:
  GEX: 20000 # default: 20000
  ATAC: 25000 # default: 25000
  ADT: 10000 # default: 5000
  HTO: 2000 # default: 2000


# --------------------------------------------------
# Command line flags
# --------------------------------------------------
# OPTIONAL
# If not specified, defaults to ''
cellbender_args: >-
  --cuda
  --fpr 0.01
  --exclude-feature-types Peaks
  --total-droplets-included 30000
